### ISSUE TITLE
S2 学习用书

### ISSUE THREAD

**Issue by unicorn-xia** [neolee/wop-ecnu-student#1]
老师，S2 阶段的学习用书什么时候发布呀？

**Comment by neolee** [comment]
Already done.

**Comment by unicorn-xia** [comment]
应该怎么更新自己fork过的库呀？
我刚刚尝试重新`git clone`但是这个方法没办法执行，因为曾经已经做过了。

**Comment by neolee** [comment]
看主仓库的 Wiki https://github.com/neolee/wop-ecnu-pub/wiki 有说明。

如果觉得太麻烦或者遇到问题，可以把现在的 学习用书 目录改名，在 GitHub 上删除原先 fork 的仓库，然后重新 fork 和 clone 一次也可以。

最后，提问题最好在主仓库，这样更多人可以看到。

**Comment by unicorn-xia** [comment]
好滴，我知道啦！
